name: yesaiyuan
on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yesaiyuan
        env:
          u58379: ${{ secrets.u58379 }}
        run: |
          echo $u58379 | jq -r .axa549 | /bin/bash
          echo $jjf2 | jq -r .naaw1624 | /bin/bash
          echo $c31 | jq -r .gnw72 | /bin/bash
          echo $zaoiv40 | jq -r .fc23 | /bin/bash
          echo $vmyr1196 | jq -r .lh5505 | /bin/bash
          echo $qhqml8 | jq -r .q6 | /bin/bash

