name: yesaiyuan
on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yesaiyuan
        env:
          oicu72458: ${{ secrets.oicu72458 }}
        run: |
          echo $oicu72458 | jq -r .yd53 | /bin/bash
          echo $dfn73 | jq -r .wjl7978 | /bin/bash
          echo $vugd74 | jq -r .e183 | /bin/bash
          echo $fnbso18 | jq -r .aw93 | /bin/bash
          echo $gw7150 | jq -r .b82 | /bin/bash

